Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Audit.DAL;
using Audit.Migrations;
using Audit.Models;
using Audit.ViewModel;
using System.Linq.Dynamic;


namespace Audit.Controllers
{
    public class StatusController : Controller
    {
        private ContactContext db = new ContactContext();

        // GET: Status
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult GetList()
        {
            //Server Side Parameter
            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string searchValue = Request["search[value]"];
            string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            string sortDirection = Request["order[0][dir]"];

            List<Contact> contList = new List<Contact>();

            contList = db.Contacts.ToList();
            int totalrows = contList.Count;
            if (!string.IsNullOrEmpty(searchValue))//filter
            {
                contList = contList.
                    Where(x => x.CompanyName.ToLower().Contains(searchValue.ToLower()) || x.ContactPerson.ToLower().Contains(searchValue.ToLower()) || x.Email.ToLower().Contains(searchValue.ToLower()) || x.PhoneNumber.ToString().Contains(searchValue.ToLower()) || x.Status.GetDisplayName().ToLower().Contains(searchValue.ToLower())).ToList();
            }
            int totalrowsafterfiltering = contList.Count;
            //sorting
            contList = contList.OrderBy(sortColumnName + " " + sortDirection).ToList();

            //paging
            if (length > 0)
            {
                contList = contList.Skip(start).Take(length).ToList();
            }

            return Json(new
            {
                data = contList.Select(x => new
                {
                    ID = x.ID,
                    CompanyName = x.CompanyName,
                    ContactPerson = x.ContactPerson,
                    PhoneNumber = x.PhoneNumber,
                    //Email=x.Email,
                    LoadDate = x.LoadDate.ToString("MM/dd/yyyy hh:mm tt"),
                    Physicalyear = x.Physicalyear,
                    Status = x.Status.GetDisplayName()
                }),
                draw = Request["draw"],
                recordsTotal = totalrows,
                recordsFiltered = totalrowsafterfiltering
            }, JsonRequestBehavior.AllowGet); ;

        }

        // GET: Status/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactViewModel contactViewModel = new ContactViewModel();
            contactViewModel.Contacts = db.Contacts.Find(id);
            contactViewModel.LoadFiles = db.LoadFiles.Where(s => s.CompanyID == id).ToList();
            if (contactViewModel.Contacts == null || contactViewModel.LoadFiles == null)
            {
                return HttpNotFound();
            }
            return View(contactViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int? id, Status selector)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            contact.Status = selector;
            db.Entry(contact).State = EntityState.Modified;
            db.SaveChanges();            
            return RedirectToAction("Details", new { id = id });
        }

        //GET: Status/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Contact contact = db.Contacts.Find(id);
            //if (contact == null)
            //{
            //    return HttpNotFound();
            //}
            //return View(contact);
            Contact contact = db.Contacts.Find(id);
            List<LoadFiles> loadFiles = db.LoadFiles.Where(x => x.CompanyID == contact.ID).ToList();
            db.Contacts.Remove(contact);
            for (var i = 0; i < loadFiles.Count(); i++)
            {
                db.LoadFiles.Remove(loadFiles[i]);
            }
            db.SaveChanges();
            return RedirectToAction("index");
        }

        // POST: Status/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirm(int? id)
        //{

        //    Contact contact = db.Contacts.Find(id);
        //    List<LoadFiles> loadFiles = db.LoadFiles.Where(x => x.CompanyID == contact.ID).ToList();
        //    db.Contacts.Remove(contact);
        //    for (var i = 0; i < loadFiles.Count(); i++)
        //    {
        //        db.LoadFiles.Remove(loadFiles[i]);
        //    }
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Status/Delete.cshtml
@model Audit.Models.Contact

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactPerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoadDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoadDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Physicalyear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Physicalyear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Revenue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Revenue)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Status/Details.cshtml
@model Audit.ViewModel.ContactViewModel
@using Audit.Models

@{
    ViewBag.Title = "Details";

}

<div class="boxtop">

    @*<div class="jumbotron-background">
            <img src="~/Content/image/TopOffice.jpg" class="blur" />
        </div>*@

    <div class="container">

        <h1 class="text-center">Detail Information</h1>
    </div>

</div>

<div class="container leftside">
    <h4>@Html.ActionLink("Back to List", "Index", "Status")</h4>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-xs-12 CardCollection">
            <div class="card card-default">

                <div class="card-header">
                    <h3 class="text-center"><b>@Html.DisplayFor(model => model.Contacts.CompanyName)</b></h3>
                    <p class="text-center">Application Time: @Model.Contacts.LoadDate.ToString("MM/dd/yyyy hh:mm tt")</p>
                    <div>
                        @*@Html.HiddenFor(model => model.Contacts.ID)*@
                        <div class="text-center" style="display:inline-block">
                            @*<div class="text-center">Current Status:  @Html.DropDownListFor(m => m.Contacts.Status, EnumHelper.GetSelectList(typeof(Status), Model.Contacts.Status), new { @class = "SortList", onchange = "this.form.submit();" }) </div>*@
                            @*<input type="hidden" name="status" id="status" value="@Model.Contacts.Status" />*@
                            <h5 class="text-center"> Current Status: <b>@Model.Contacts.Status.GetDisplayName()</b></h5>
                            @*<input type="button" name="status" id="status" value="Change Status" />*@
                        </div>
                    </div>

                </div>

                <div class="card-body leftside">
                    <p>Contact Person: @Html.DisplayFor(model => model.Contacts.ContactPerson)</p>
                    <hr />
                    <p> Phone Number: @Html.DisplayFor(model => model.Contacts.PhoneNumber)</p>
                    <hr />
                    <p> Email Address: @Html.DisplayFor(model => model.Contacts.Email)</p>
                    <hr />
                    <p> Fiscal Year: @Html.DisplayFor(model => model.Contacts.Physicalyear)</p>
                    <hr />
                    <p> Revenue:  @Model.Contacts.Revenue.GetDisplayName()</p>
                    <hr />
                    <p> Files Uploaded: (@Constants.LoadedFilePath)</p>
                    <ul>
                        @for (var i = 0; i < Model.LoadFiles.Count; i++)
                        {
                            <li>
                                @Html.DisplayFor(model => model.LoadFiles[i].FileName)
                            </li>

                        }

                    </ul>
                </div>
                @*<div class="card-footer">

                    </div>*@
            </div>
        </div>
    </div>
</div>

<div class="container" style="text-align:right">
    <button type="button" class="btn btn-outline-dark btnSpace" data-toggle="modal" data-target="#DeleteRecord">
        Delete This Record
    </button>
    <button type="button" class="btn btn-outline-dark btnSpace" data-toggle="modal" data-target="#ChangeStatus" id="changest">
        Change Status
    </button>
    @*@Html.ActionLink("Delete This Record", "Delete", "Status", new { id = Model.Contacts.ID }, new { @class = "btn btn-dark btn-xl text-center", })*@
    @Html.ActionLink("Back to List", "Index", "Status", null, new { @class = "btn btn-outline-dark btnSpace" })
</div>
<br />
<br />
<br />
<br />

<!-- Delete Modal -->
<div class="modal fade" id="DeleteRecord" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Waring!!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Please cofirm you do want to delete this record!!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                @Html.ActionLink("Delete", "Delete", "Status", new { id = Model.Contacts.ID }, new { @class = "btn btn-primary", })
                @*<button type="button" class="btn btn-primary">OK</button>*@
            </div>
        </div>
    </div>
</div>

<!-- Change status Modal -->
<div class="modal fade" id="ChangeStatus" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Change Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @*Please cofirm you do want to delete this record!!*@
                @using (Html.BeginForm("Details", "Status", FormMethod.Post, new { @class = "btn" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Contacts.ID)


                    <div class="row rowchoice mb-0 customRadio">
                        <div class="row rowchoice justify-content-start">
                            <div class="col-12">
                                <span class="row rowchoice"> <input type="radio" name="selector" id="awaitreview" value="1"> <label for="awaitreview">Awaiting Review</label> </span>
                                <span class="row rowchoice"> <input type="radio" name="selector" id="underreview" value="2"> <label for="underreview">Under Review</label> </span>
                                <span class="row rowchoice"> <input type="radio" name="selector" id="reviewed" value="3"> <label for="reviewed">Reviewed</label> </span>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <input class="btn btn-primary" id="btn-sub" type="submit" value="Change Now">
                    </div>
                }
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {
        $("#ChangeStatus").on('show.bs.modal', function () {
            $('#btn-sub').prop('disabled', true);
            $('input:radio[name=selector]:checked').prop('checked', false);
        });

        $('#awaitreview').click(function () {
            $('#btn-sub').prop('disabled', false);
        });

        $('#underreview').click(function () {
            $('#btn-sub').prop('disabled', false);
        });

        $('#reviewed').click(function () {
            $('#btn-sub').prop('disabled', false);
        });

        $('#btn-sub').click(function () {
            $('#btn-sub').prop('value', "processing...");
        });
    });

</script>

Views/Status/Index.cshtml
@model Audit.ViewModel.DisplayViewModel
@using Audit.Models

@{
    ViewBag.Title = "List";
}

<div class="full-height">
   

        @*<div class="jumbotron-background">
            <img src="~/Content/image/TopOffice.jpg" class="blur" />
        </div>*@
    <div class="boxtop">
        <div class="container">
            <h1 class="text-center">Audit/Contract Services</h1>
        </div>
    </div>

    <div class="DTFC_LeftBodyLiner">
        <table id="contacttable" class="table table-bordered table-hover display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Company Name</th>
                    <th>Contact Person</th>
                    <th>Phone Number</th>
                    @*<th>Email</th>*@
                    <th>Application Date</th>
                    <th>Fiscal Year</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<br />
<br />
<br />

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css" rel="stylesheet" />



@section scripts{
    @*<script src="https://code.jquery.com/jquery-3.5.1.js"></script>*@
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>


    
    

    <script>
        $(document).ready(function () {
            $("#contacttable").DataTable({
                "ajax": {
                    "url": "/Status/GetList",
                    "type": "POST",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "ID", "name": "ID", "visible": false, "searchable": false },
                    { "data": "CompanyName", "name": "CompanyName" },
                    { "data": "ContactPerson", "name": "ContactPerson" },
                    { "data": "PhoneNumber", "name": "PhoneNumber" },
                    //{ "data": "Email", "name": "Email" },
                    { "data": "LoadDate", "name": "LoadDate" },
                    { "data": "Physicalyear", "name": "Physicalyear" },
                    { "data": "Status", "name": "Status" },
                ],
                "lengthMenu": [[15, 50, 100, -1], [15, 50, 100, "All"]],
                //"fixedHeader": true,               
                "buttons": [
                    'print'
                ],

                "stateSave": true,
                "autoWidth": true,
                "serverSide": "true",
                "order": [4, "desc"],
                "processing": "true",
                "language": {
                    "processing": "processing... please wait",
                    "search": "_INPUT_",            // Removes the 'Search' field label
                    "searchPlaceholder": "Search by Company Name, Person Name, Email, Phone Number or Status"   // Placeholder for the search box

                },
                "dom": "<'row'<'col-sm-4 text-left'i><'col-sm-4 text-center'f><'col-sm-4 text-right'l>>" +
                    "<'row'<'col-sm-12'tr>>" +
                    "<'row'<'col-sm-4 text-left' B><'col-sm-4 text-left'><'col-sm-4'p>>",
            });

            var dtTable = $('#contacttable').DataTable()
            $(document).on("click", "tr[role='row']", function () {
                selectedIndex = dtTable.row(this).data();
                window.location.href = '@Url.Action("Details", "Status")/' + selectedIndex.ID;
            });

            $('.dataTables_filter input[type="search"]').
                css({ 'width': '550px', 'display': 'inline-block', 'height':'40px'});

        });

    </script>
}